### ISSUE TITLE
[meta] Well known Symbols 

### ISSUE THREAD

**Issue by BobVarioa** [CanadaHonk/porffor#140]
- [ ] `Symbol.asyncIterator`, related to #117 #97 #72 
- [ ] `Symbol.hasInstance`
- [ ] `Symbol.isConcatSpreadable`
- [ ] `Symbol.iterator`, related to #97 #72 
- [ ] `Symbol.match`, related to #110 
- [ ] `Symbol.matchAll`, related to #110 
- [ ] `Symbol.replace`
- [ ] `Symbol.search`
- [ ] `Symbol.species`
- [ ] `Symbol.split`
- [ ] `Symbol.toPrimitive`
- [ ] `Symbol.toStringTag`
- [ ] `Symbol.unscopables`

**Comment by CanadaHonk** [comment]
All issues are being automatically closed as Porffor was recently almost entirely rewritten. Please reopen if still reproducable/relevant. See #344 for more information, thanks for understanding.
