### ISSUE TITLE
[meta] Function methods and properties

### ISSUE THREAD

**Issue by BobVarioa** [CanadaHonk/porffor#90]
- [ ] [`apply()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply)
- [ ] [`bind()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind)
- [ ] [`call()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call)
- [x] [`toString()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/toString) [^2]
- [ ] [`.arguments`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/arguments)
- [ ] [`.length`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/length) [^1]
- [ ] [`.name`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name) [^1]
- [ ] [`.prototype`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/prototype)

[^1]: implemented but not available at runtime
[^2]: technically okay, but it should be plenty possible to retrieve the source text

**Comment by CanadaHonk** [comment]
All issues are being automatically closed as Porffor was recently almost entirely rewritten. Please reopen if still reproducable/relevant. See #344 for more information, thanks for understanding.
